[project]
name = "guardrails"
version = "0.1.0"
description = "Project to explore guardrails for agents"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.30.1",
    "openai-agents>=0.3.2",
    "python-dotenv>=1.1.1",
]
